version: '3.3'
services:
  web:
    image: dataflow-editor:latest
    build:
      context: .
      dockerfile: DockerfileNamespace
      args:
        DIRPATH: ${DIRPATH}
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - "/app/node_modules"
      - ".:/app"
    env_file:
      - .env
